name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [16, 18, 20]

    steps:
      - uses: actions/checkout@v4

      # - name: Node ${{ matrix.node }} sample
      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node }}
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t lucasnfarias/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }} .

      - name: Push image
        run: docker push lucasnfarias/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}
